---
title: "Tüseb"
author: "beyza"
date: "2022-12-08"
output: html_document
---

load libraries
```{r}
library(argparse)
library(findpython)
library(sp)
library(SeuratObject)
library(Seurat)
library(hdf5r)
library(devtools)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(patchwork)
library(devtools)
library(AUCell)
library(Seurat)
library(GSEABase)
library(Rtsne)
library(Seurat)

```



For Creat SeuratObject 
```{r}

file_obj <- Read10X_h5(filename = "file.h5", 
                             use.names = TRUE,
                             unique.features = TRUE)

Seurat_file <- CreateSeuratObject(counts = file_obj)

```


Seurat
1.MTReads
```{r}
Seurat_file[["percent.mt"]] <- PercentageFeatureSet(Seurat_file, pattern = "^MT-")

VlnPlot(Seurat_file, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

2. filtering
```{r}
Seurat_file <- subset(Seurat_file, subset =nFeature_RNA > 200 & nFeature_RNA <4500 & percent.mt < 17)
```

3. Normalize data
```{r}
#pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
Seurat_file <- NormalizeData(Seurat_file)
```


4. Identify highly variable features
```{r}
Seurat_file <- FindVariableFeatures(Seurat_file, selection.method = "vst", nfeatures = 3863)
```


5. Scaling
```{r}
all.genes <- rownames(Seurat_file)
Seurat_file <- ScaleData(Seurat_file, features = all.genes)
```


6.Perform linear dimensionality reduction
```{r}
Seurat_file <- RunPCA(Seurat_file, features = VariableFeatures(object = Seurat_file))
```


7. umap
```{r}

Seurat_file <- FindNeighbors(Seurat_Gfile, dims = 1:10)
Seurat_file <- FindClusters(Seurat_file, resolution = 0.5)
Seurat_file <- RunUMAP(Seurat_file, dims = 1:15)
DimPlot(Seurat_file, reduction = "umap")
```







