---
title: "slingshot"
author: "beyza"
date: "2023-06-14"
output: html_document
---


load libraries
```{r}
library(slingshot)
library(Seurat)
library(ggplot2)
library(jpeg)
```






2.slingshot
```{r}
rd <- GetAssayData(object = donors, assay = "RNA")
cl <- Idents(donors)

```

3.1Gene Filtering
```{r}
sce <- SingleCellExperiment(assays = list(counts = matrix_data))

# Gen filtresini uygulayın
geneFilter <- apply(assays(sce)$counts, 1, function(x) {
  sum(x >= 3) >= 10
})
sce <- sce[geneFilter, ]
```

3.2 normalization
```{r}
# FQnorm fonksiyonunu tanımlayın
FQnorm <- function(counts) {
  rk <- apply(counts, 2, rank, ties.method = 'min')
  counts.sort <- apply(counts, 2, sort)
  refdist <- apply(counts.sort, 1, median)
  norm <- apply(rk, 2, function(r) { refdist[r] })
  rownames(norm) <- rownames(counts)
  return(norm)
}

# SingleCellExperiment nesnesindeki counts matrisine FQnorm uygulayın
assays(sce)$norm <- FQnorm(assays(sce)$counts)
```

3.3 Dimensionality Reduction
```{r}
# PCA analizini uygulayın
pca <- prcomp(t(log1p(assays(sce)$norm)), scale. = FALSE)
rd1 <- pca$x[, 1:2]

png("p1.png")

# Grafik çizimini yapın
plot(rd1, col = rgb(0, 0, 0, .5), pch = 16, asp = 1)

# Grafik cihazını kapatın
dev.off()

```

```{r}
library(uwot)
# UMAP analizini uygulayın
rd2 <- uwot::umap(t(log1p(assays(sce)$norm)))
colnames(rd2) <- c('UMAP1', 'UMAP2')

# İki bileşeni kullanarak plot yapın
png("p2.png")
plot(rd2, col = rgb(0, 0, 0, .5), pch = 16, asp = 1)

# Grafik cihazını kapatın
dev.off()

# reducedDims'e PCA ve UMAP boyutlarını atayın
reducedDims(sce) <- SimpleList(PCA = rd1, UMAP = rd2)


```


3.4Clustering Cells
```{r}
# reducedDims'e PCA ve UMAP boyutlarını atayın
reducedDims(sce) <- SimpleList(PCA = rd1, UMAP = rd2)

library(mclust, quietly = TRUE)
# Mclust kullanarak rd1 için sınıflandırmayı yapın
cl1 <- Mclust(rd1)$classification

# colData(sce) içinde GMM sütununu oluşturun ve cl1 değerlerini atayın
colData(sce)$GMM <- cl1

# RColorBrewer kütüphanesini yükleyin
library(RColorBrewer)

# rd1'ı renkli nokta grafiği ile görselleştirin
png("p3.png")
plot(rd1, col = brewer.pal(9,"Set1")[cl1], pch=16, asp = 1)
dev.off()

```

```{r}
cl2 <- kmeans(rd1, centers = 4)$cluster
colData(sce)$kmeans <- cl2

png("p4.png")
plot(rd1, col = brewer.pal(9,"Set1")[cl2], pch=16, asp = 1)
dev.off()
```


4. using slingshot
```{r}
sce <- slingshot(sce, clusterLabels = 'GMM', reducedDim = 'PCA')
library(grDevices)
colors <- colorRampPalette(brewer.pal(11,'Spectral')[-6])(100)
plotcol <- colors[cut(sce$slingPseudotime_1, breaks=100)]

png("p5.png")
plot(reducedDims(sce)$PCA, col = plotcol, pch=16, asp = 1)
dev.off()
lines(SlingshotDataSet(sce), lwd=2, col='black')

```
```{r}
png("p6.png")
plot(reducedDims(sce)$PCA, col = brewer.pal(9,'Set1')[sce$GMM], pch=16, asp = 1)
dev.off()
lines(SlingshotDataSet(sce), lwd=2, type = 'lineages', col = 'black')
```
5.Downstream Analysis
5.1 Identifying temporally dynamic genes
```{r}
library(tradeSeq)

# fit negative binomial GAM
sce <- fitGAM(sce)

# test for dynamic expression
ATres <- associationTest(sce)

topgenes <- rownames(ATres[order(ATres$pvalue), ])[1:250]
pst.ord <- order(sce$slingPseudotime_1, na.last = NA)
heatdata <- as.matrix(assays(sce)$counts[topgenes, pst.ord])
heatclus <- sce$GMM[pst.ord]

png("p7.png")
heatmap(log1p(heatdata), Colv = NA,
        ColSideColors = brewer.pal(9, "Set1")[heatclus])
dev.off()
```

```{r}
lin1 <- getLineages(matrix_data, cl, start.clus = '1')
png("p8.png")
plot(rd, col = brewer.pal(9,"Set1")[cl], asp = 1, pch = 16)
dev.off()
lines(SlingshotDataSet(lin1), lwd = 3, col = 'black')
```



